### ISSUE TITLE
Liber Panoptica TODO

### ISSUE THREAD

**Issue by nstephenh** [nstephenh/moreus-heresy#1]
Liber Panoptica:

- [x] Horus Heresy: Age of Darkness Core Rulebook
- [x] Campaigns in the Age of Darkness: The Siege of Cthonia 
- [ ] Liber Astartes & Hereticus
- - [ ] Weapon and Equipment Upgrades ensure bayonettes are selectable
- - [ ] Denote compulsory troops?
- - [ ] Unit, weapon, rite of war changes
- [ ] Liber Astartes
- [ ] Liber Hereticus
- [ ] Legacies of the Age of Darkness 
- [ ] Exemplary Battles in the Age of Darkness
- [ ] Ka’Bandha - Warhammer Community
- [ ] Liber Mechanicum
- [ ] Legacies of the Age of Darkness: Mechanicum 
- [ ] Liber Imperium 
- [ ] Legacies of the Age of Darkness: Solar Auxilia 
- [ ] Legacies of the Age of Darkness: The Imperialis Militia
- [ ] ARMOURY OF THE AGE OF DARKNESS
- - [x] Additional Special Rules 
- - [ ] Panoptica Weapon Profiles
- - [ ] Extrinsica Melee Weapons

**Comment by nstephenh** [comment]
How to handle Mutli-Melta Suspensor Web?

**Comment by nstephenh** [comment]
Missing rites of war:
Armored spearhead (needs "compulsory troops" handling)

**Comment by nstephenh** [comment]
Left in Liber Astartes:
Confirm Inner Circle Knights Cenobium what should/shouldn't be a character
Blood angels advanced reaction

**Comment by nstephenh** [comment]
Liber Hireticus:
Compulsory troops
Dark Channelling
Coils of the Hydra
